### ISSUE TITLE
Samples aren't working at all

### ISSUE THREAD

**Issue by ybizeul** [thomaslwq/react-admin#2]
Using latest versions of Safari or Chrome, samples just don't work

Safari always reloads the same dashboards even when trying to display a different page
Chrome completely offsets the page to the right or the bottom

**Comment by thomaslwq** [comment]
hi dude! Thank you for your feedback.I clone the project but it seems that work fine in my computer. There is a online [react-admin](http://linweiqin.cn:3000/) you can check.Maybe you can take a snapshot of what it is in your browser so that I can find the problem.

**Comment by ybizeul** [comment]
It happens when I browse one menu after the other.

- First the menu close and open again quickly every time you change.
- Then Dashboard 2 has Profile Completion gauge half cut
- Beginning with UI Element, the page never changes it's always the same dashboard.

I could not reproduce the offset.

Finally, I'm spooked by the 38k+ vulnerabilities !

Take care
